### ISSUE TITLE
New subscribers not being added to automation

### ISSUE THREAD

**Issue by Obblesnatch** [dotmailer/dotmailer-magento-extension#311]
Hello,

We're having an issue where new subscribers aren't being added to the automation we've set in admin. We believe the problem is coming from **src/app/code/community/Dotdigitalgroup/Email/Model/Newsletter/Observer.php** 
On the site, we require users to confirm their email so their status is unconfirmed. This causes the action to return early (see line 88) before being added to the automation. This is okay, however because the contact is saved just before returning, after they confirm their email they return in this observer and the isSubscriberNew flag is set to false. This causes the check in the _addSubscriberToAutomation function to not pass, and so the customer isn't added to the automation. We've temporarily fixed the problem by removing the return on line 88.

This may be causing the email to be sent before the full customer data is import into Dotdigital. The language for example isn't being added in time so the email is sent in the wrong language.

Is there a better/official fix for this?

Thanks!

**Comment by adeelq** [comment]
@Obblesnatch Thanks for reporting this. We have added this to current sprint.

**Comment by adeelq** [comment]
@Obblesnatch This is fixed in latest release 6.4.12. Please see the release notes as well and Please upgrade.

**Comment by Obblesnatch** [comment]
Hi @adeelq ,

In the latest release I don't see any mention of them being added to the automation. It's just fixes for re-subscribers. Our issue is related to new subscribers that need to confirm their email address before being marked as subscribed. They never hit the automation as the first time they pass in the observer they're not subscribed, and the second time they hit the observer they're not technically 'new'

**Comment by Obblesnatch** [comment]
Hi @adeelq ,

Is there an update on this issue? We're still having problems with customers not being added to the automation as they need to confirm their email. As mentioned above, we've commented line 88 to get it to work, but it's not a proper fix.

Thanks
